const SUPABASE_URL='https://pgdoxpcwtqjbmqvzihhs.supabase.co';
const SUPABASE_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnZG94cGN3dHFqYm1xdnppaGhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU4NTQ4NTMsImV4cCI6MjEwMTQzMDg1M30.IRTf_pm2heQIaBWE80r56dmc2gUJ5SgGEe4Br2EQFYs';
const headers={apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`};
let collections=[];let lessonWords=[];let current=0;let phase='discover';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function show(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#page-title').textContent={home:'Inicio',collections:'Aprender',lesson:'Lección'}[view]||'English Lab';window.scrollTo({top:0,behavior:'smooth'});}
$$('.nav-item').forEach(b=>b.onclick=()=>show(b.dataset.view));document.addEventListener('click',e=>{const g=e.target.closest('[data-go]');if(g)show(g.dataset.go)});$('#start-learning').onclick=()=>show('collections');$('#reload').onclick=loadCollections;
async function api(path){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{headers});if(!r.ok)throw new Error(await r.text());return r.json();}
async function loadCollections(){const grid=$('#collections-grid');grid.innerHTML='<div class="loading">Cargando colecciones reales…</div>';try{collections=await api('vocabulary_collections?select=id,title,description,level,collection_code,topic&status=eq.active&is_public=eq.true&order=title.asc');grid.innerHTML=collections.map((c,i)=>`<article class="collection-card"><span class="tag">${c.level||'A1'} · ${String(i+1).padStart(2,'0')}</span><h4>${escapeHtml(c.title.replace(/^A1 · /,''))}</h4><p>${escapeHtml(c.description||c.topic||'Colección temática')}</p><button class="primary" data-collection="${c.id}">Comenzar lección</button></article>`).join('');$$('[data-collection]').forEach(b=>b.onclick=()=>startLesson(b.dataset.collection));}catch(err){grid.innerHTML=`<div class="loading"><strong>No pude leer las colecciones.</strong><br>${escapeHtml(err.message)}</div>`}}
async function startLesson(id){const c=collections.find(x=>x.id===id);show('lesson');$('#lesson-title').textContent=(c?.title||'Lección').replace(/^A1 · /,'');$('#lesson-kicker').textContent='LECCIÓN · 6 PALABRAS';$('#lesson-card').className='lesson-card';$('#lesson-card').innerHTML='<div class="loading">Preparando vocabulario real…</div>';try{const rows=await api(`collection_words?select=position,vocabulary_words(id,english,spanish,pronunciation,example_en,example_es,visual_hint)&collection_id=eq.${encodeURIComponent(id)}&order=position.asc&limit=6`);lessonWords=rows.map(r=>r.vocabulary_words).filter(Boolean);if(!lessonWords.length)throw new Error('Esta colección todavía no tiene palabras disponibles para el usuario público.');current=0;phase='discover';renderLesson();}catch(err){$('#lesson-card').innerHTML=`<h4>No pude preparar esta lección</h4><p>${escapeHtml(err.message)}</p><button class="ghost" data-go="collections">Volver</button>`}}
function progress(){const stages=3;const total=Math.max(1,lessonWords.length*stages);const phaseIdx={discover:0,recognize:1,recall:2,done:3}[phase];const done=Math.min(total,current*stages+phaseIdx);$('#progress-label').textContent=`${done} / ${total}`;$('#progress-bar').style.width=`${(done/total)*100}%`;}
function renderLesson(){progress();if(phase==='done'){return renderDone()}const w=lessonWords[current];if(!w)return renderDone();if(phase==='discover')renderDiscover(w);if(phase==='recognize')renderRecognize(w);if(phase==='recall')renderRecall(w);}
function renderDiscover(w){$('#lesson-card').innerHTML=`<span class="hero-kicker">DESCUBRIR</span><div class="word">${escapeHtml(w.english)}</div><div class="translation">${escapeHtml(w.spanish)}</div>${w.pronunciation?`<p>Pronunciación: <strong>${escapeHtml(w.pronunciation)}</strong></p>`:''}${w.example_en?`<div class="example"><strong>${escapeHtml(w.example_en)}</strong>${w.example_es?`<br><span>${escapeHtml(w.example_es)}</span>`:''}</div>`:''}<div class="lesson-actions"><button class="primary" id="next-phase">Ya la vi · practicar</button></div>`;$('#next-phase').onclick=()=>{phase='recognize';renderLesson()}}
function distractors(w){const pool=lessonWords.filter(x=>x.id!==w.id).map(x=>x.spanish);return shuffle([w.spanish,...shuffle(pool).slice(0,3)]).slice(0,4)}
function renderRecognize(w){const opts=distractors(w);$('#lesson-card').innerHTML=`<span class="hero-kicker">RECONOCER</span><p>¿Qué significa esta palabra?</p><div class="word">${escapeHtml(w.english)}</div><div class="options">${opts.map(o=>`<button class="option" data-answer="${escapeAttr(o)}">${escapeHtml(o)}</button>`).join('')}</div><div class="feedback" id="feedback"></div>`;$$('.option').forEach(b=>b.onclick=()=>{const ok=b.dataset.answer===w.spanish;$$('.option').forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');if(!ok){const right=$$('.option').find(x=>x.dataset.answer===w.spanish);right?.classList.add('correct')}$('#feedback').textContent=ok?'¡Muy bien!':'Mira la respuesta correcta.';$('#feedback').className='feedback '+(ok?'success':'error');setTimeout(()=>{phase='recall';renderLesson()},850)})}
function renderRecall(w){$('#lesson-card').innerHTML=`<span class="hero-kicker">RECORDAR</span><p>Escribe en inglés:</p><div class="translation">${escapeHtml(w.spanish)}</div><input class="answer-input" id="answer" autocomplete="off" placeholder="Escribe la palabra"/><div class="feedback" id="feedback"></div><div class="lesson-actions"><button class="primary" id="check">Comprobar</button></div>`;const input=$('#answer');setTimeout(()=>input.focus(),0);const check=()=>{const val=input.value.trim().toLowerCase();const ok=val===w.english.trim().toLowerCase();$('#feedback').textContent=ok?'¡Correcto!':'Respuesta: '+w.english;$('#feedback').className='feedback '+(ok?'success':'error');input.disabled=true;$('#check').disabled=true;setTimeout(()=>{current++;phase=current>=lessonWords.length?'done':'discover';renderLesson()},900)};$('#check').onclick=check;input.onkeydown=e=>{if(e.key==='Enter')check()}}
function renderDone(){progress();$('#progress-label').textContent=`${lessonWords.length*3} / ${lessonWords.length*3}`;$('#progress-bar').style.width='100%';$('#lesson-card').innerHTML=`<img src="assets/escudo.png" alt="Escudo" style="width:96px"><span class="hero-kicker">LECCIÓN COMPLETADA</span><h4>¡Muy buen trabajo!</h4><p>Completaste descubrir, reconocer y recordar con ${lessonWords.length} palabras reales.</p><div class="lesson-actions"><button class="primary" data-go="collections">Elegir otra colección</button><button class="ghost" id="repeat">Repetir</button></div>`;$('#repeat').onclick=()=>{current=0;phase='discover';renderLesson()}}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}function escapeAttr(s=''){return escapeHtml(s)}
loadCollections();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(()=>{}));
