create schema if not exists private;

do $$ begin create type public.app_role as enum ('teacher','student'); exception when duplicate_object then null; end $$;
do $$ begin create type public.institution_role as enum ('student','teacher','institution_admin','superadmin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.membership_status as enum ('active','inactive'); exception when duplicate_object then null; end $$;
do $$ begin create type public.mastery_state as enum ('new','learning','review','mastered'); exception when duplicate_object then null; end $$;
do $$ begin create type public.activity_type as enum ('association','listening','writing','recall'); exception when duplicate_object then null; end $$;
do $$ begin create type public.activity_source as enum ('daily_mission','weekly_mission','game','assessment','free_practice','offline_sync'); exception when duplicate_object then null; end $$;
do $$ begin create type public.attempt_outcome as enum ('correct','incorrect','skipped','no_answer'); exception when duplicate_object then null; end $$;

create table if not exists public.schools(id uuid primary key default gen_random_uuid(), name text not null, municipality text, department text, country_code char(2) not null default 'CO', created_at timestamptz not null default now());
create table if not exists public.academic_years(id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id), name text not null, starts_on date, ends_on date);
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade, school_id uuid references public.schools(id), role public.app_role not null, display_alias text not null, profile_photo_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.groups(id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id), teacher_id uuid references auth.users(id), name text not null, grade text, join_code text not null unique, archived_at timestamptz, created_at timestamptz not null default now(), academic_year_id uuid references public.academic_years(id), grade_id uuid, status text not null default 'active', section_code text);
create table if not exists public.group_members(group_id uuid not null references public.groups(id) on delete cascade, student_id uuid not null references auth.users(id) on delete cascade, status public.membership_status not null default 'active', joined_at timestamptz not null default now(), ended_at timestamptz, end_reason text, primary key(group_id,student_id));
create table if not exists private.institution_memberships(id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id), user_id uuid not null references auth.users(id) on delete cascade, role public.institution_role not null, status text not null default 'active', created_at timestamptz not null default now(), unique(school_id,user_id,role));
create table if not exists private.teacher_assignments(id uuid primary key default gen_random_uuid(), membership_id uuid not null references private.institution_memberships(id) on delete cascade, group_id uuid not null references public.groups(id) on delete cascade, academic_year_id uuid not null references public.academic_years(id), status text not null default 'active', created_at timestamptz not null default now(), unique(membership_id,group_id,academic_year_id));
create table if not exists private.super_admins(school_id uuid not null references public.schools(id), user_id uuid not null references auth.users(id), primary key(school_id,user_id));
create table if not exists private.practice_session_receipts(session_id uuid primary key, student_id uuid not null references auth.users(id), result jsonb not null, created_at timestamptz not null default now());
create table if not exists private.institution_audit_log(id bigint generated always as identity primary key, school_id uuid not null references public.schools(id), actor_id uuid not null references auth.users(id), action text not null, target_type text not null, target_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists private.group_membership_events(id bigint generated always as identity primary key, group_id uuid not null references public.groups(id), student_id uuid not null references auth.users(id), actor_id uuid not null references auth.users(id), event_type text not null, occurred_at timestamptz not null default now());

create table if not exists public.vocabulary_words(id uuid primary key default gen_random_uuid(), english text not null, spanish text not null, category text not null, difficulty smallint not null default 1, pronunciation text, audio_path text, image_path text, visual_hint text, example_en text not null, example_es text not null, priority smallint not null default 5, created_at timestamptz not null default now(), unit_code text not null unique, unit_type text not null default 'word', lemma text not null, accepted_forms jsonb not null default '[]', learning_unit_id text not null unique, updated_at timestamptz not null default now());
create table if not exists public.learning_routes(id uuid primary key default gen_random_uuid(), school_id uuid not null references public.schools(id), route_code text not null unique, level text not null, version integer not null, title text not null, status text not null default 'draft', assignment_count integer not null default 0, lesson_count integer not null default 0, content_fingerprint text, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), mastery_threshold numeric not null default 0.800);
create table if not exists public.learning_lessons(id uuid primary key default gen_random_uuid(), route_id uuid not null references public.learning_routes(id) on delete cascade, collection_id uuid not null, lesson_number integer not null, route_lesson_position integer not null, title text not null, unit_count smallint not null, created_at timestamptz not null default now(), purpose text, unique(route_id,route_lesson_position));
create table if not exists public.learning_lesson_units(lesson_id uuid not null references public.learning_lessons(id) on delete cascade, collection_id uuid not null, word_id uuid not null references public.vocabulary_words(id), lesson_unit_position smallint not null, source_collection_position integer not null, primary key(lesson_id,word_id), unique(lesson_id,lesson_unit_position));

create table if not exists public.practice_sessions(id uuid primary key default gen_random_uuid(), student_id uuid not null references auth.users(id), assignment_id uuid, started_at timestamptz not null default now(), completed_at timestamptz, xp_earned integer not null default 0, coins_earned integer not null default 0, client_session_id text, source public.activity_source not null default 'daily_mission', source_id uuid, route_id uuid references public.learning_routes(id), lesson_id uuid references public.learning_lessons(id), session_kind text not null default 'learning', run_mode text not null default 'normal', status text not null default 'in_progress', last_activity_at timestamptz not null default now(), snapshot jsonb not null default '{}', snapshot_version integer not null default 0, client_context jsonb not null default '{}', reward_eligible_word_ids uuid[] not null default '{}', unique(student_id,client_session_id));
create table if not exists public.practice_attempts(id bigint generated always as identity primary key, session_id uuid not null references public.practice_sessions(id) on delete cascade, word_id uuid not null references public.vocabulary_words(id), activity_type public.activity_type not null, answer_text text, is_correct boolean not null, response_time_ms integer not null, attempt_number smallint not null default 1, answered_at timestamptz not null default now(), client_event_id text, outcome public.attempt_outcome, source public.activity_source not null default 'daily_mission', source_id uuid, assistance_level smallint not null default 0, counts_for_mastery boolean not null default true, can_generate_reward boolean not null default true, response_metadata jsonb not null default '{}', answer_normalized text, lesson_unit_position smallint, activity_position smallint);
create unique index if not exists uq_attempt_client_event on public.practice_attempts(session_id,client_event_id) where client_event_id is not null;
create unique index if not exists uq_route_activity_once on public.practice_attempts(session_id,word_id,activity_type) where lesson_unit_position is not null;
create table if not exists public.student_word_progress(student_id uuid not null references auth.users(id), word_id uuid not null references public.vocabulary_words(id), assignment_id uuid, mastery_state public.mastery_state not null default 'new', interval_days integer not null default 0, ease_factor numeric not null default 2.30, correct_streak integer not null default 0, total_attempts integer not null default 0, correct_attempts integer not null default 0, last_response_time_ms integer, last_reviewed_at timestamptz, next_review_at timestamptz not null default now(), updated_at timestamptz not null default now(), mastered_at timestamptz, last_change_source text, primary key(student_id,word_id));
create table if not exists public.student_lesson_progress(student_id uuid not null references auth.users(id), route_id uuid not null references public.learning_routes(id), lesson_id uuid not null references public.learning_lessons(id), status text not null default 'in_progress', mastery_status text not null default 'in_progress', unlocked_at timestamptz not null default now(), started_at timestamptz, finished_at timestamptz, attempt_count integer not null default 0, last_attempt_at timestamptz, last_correct integer not null default 0, last_total integer not null default 0, last_percentage numeric not null default 0, best_correct integer not null default 0, best_total integer not null default 0, best_percentage numeric not null default 0, last_result jsonb, best_result jsonb, needs_review_word_ids uuid[] not null default '{}', by_activity jsonb not null default '{}', updated_at timestamptz not null default now(), primary key(student_id,route_id,lesson_id));
create table if not exists public.student_stats(student_id uuid primary key references auth.users(id), total_xp integer not null default 0, coins integer not null default 0, current_streak integer not null default 0, longest_streak integer not null default 0, last_practice_date date, updated_at timestamptz not null default now());
create table if not exists public.reward_events(id bigint generated always as identity primary key, student_id uuid not null references auth.users(id), client_event_id text not null, source public.activity_source not null, source_id uuid, xp_delta integer not null default 0, coin_delta integer not null default 0, reason text not null, created_at timestamptz not null default now(), unique(student_id,client_event_id,reason));

create or replace function private.normalize_practice_answer(value text) returns text language sql immutable set search_path='' as $$ select btrim(regexp_replace(regexp_replace(regexp_replace(lower(trim(replace(replace(replace(replace(coalesce(value,''),'’',''''),'‘',''''),'ʼ',''''),'`',''''))),'[[:space:]]+',' ','g'),'((\.{2,}|…)+)[[:space:]]*$','','g'),'[.?!]+[[:space:]]*$','','g')); $$;
create or replace function private.current_institution_role(target_school_id uuid) returns public.institution_role language sql stable security definer set search_path='' as $$ select im.role from private.institution_memberships im where im.school_id=target_school_id and im.user_id=auth.uid() and im.status='active' order by case im.role when 'superadmin' then 4 when 'institution_admin' then 3 when 'teacher' then 2 else 1 end desc limit 1; $$;
create or replace function private.has_institution_role(target_school_id uuid, allowed_roles public.institution_role[]) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and (exists(select 1 from private.institution_memberships m where m.school_id=target_school_id and m.user_id=auth.uid() and m.status='active' and m.role=any(allowed_roles)) or ('superadmin'::public.institution_role=any(allowed_roles) and exists(select 1 from private.super_admins s where s.school_id=target_school_id and s.user_id=auth.uid()))); $$;
create or replace function private.is_group_member(target_group_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.group_members gm where gm.group_id=target_group_id and gm.student_id=auth.uid() and gm.status='active'); $$;
create or replace function private.can_manage_group(target_group_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and exists(select 1 from public.groups g where g.id=target_group_id and (private.has_institution_role(g.school_id,array['institution_admin'::public.institution_role,'superadmin'::public.institution_role]) or exists(select 1 from private.teacher_assignments ta join private.institution_memberships im on im.id=ta.membership_id where ta.group_id=g.id and ta.status='active' and im.user_id=auth.uid() and im.status='active' and im.role='teacher'))); $$;
create or replace function private.shares_group_with(target_student_id uuid) returns boolean language sql stable security definer set search_path='' as $$ select auth.uid() is not null and exists(select 1 from public.group_members gm join public.groups g on g.id=gm.group_id join private.teacher_assignments ta on ta.group_id=g.id and ta.status='active' join private.institution_memberships im on im.id=ta.membership_id where gm.student_id=target_student_id and gm.status='active' and g.status='active' and g.archived_at is null and im.user_id=auth.uid() and im.role='teacher' and im.status='active' and im.school_id=g.school_id); $$;

create or replace function public.get_my_auth_context() returns jsonb language plpgsql stable security definer set search_path='' as $$ declare viewer uuid:=auth.uid(); result jsonb; begin if viewer is null then raise exception 'Sesión requerida'; end if; select jsonb_build_object('user_id',viewer,'display_alias',p.display_alias,'school_id',p.school_id,'role',case when p.school_id is null then null else private.current_institution_role(p.school_id)::text end,'profile_photo_path',p.profile_photo_path) into result from public.profiles p where p.id=viewer; return coalesce(result,jsonb_build_object('user_id',viewer,'role',null)); end $$;

create or replace function public.start_route_lesson_session_v1(target_route_code text,target_lesson_id uuid,provided_client_session_id text,provided_client_context jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare viewer uuid:=auth.uid(); route_row public.learning_routes%rowtype; lesson_row public.learning_lessons%rowtype; existing public.practice_sessions%rowtype; created_id uuid; eligible uuid[]; ctx jsonb:=coalesce(provided_client_context,'{}'::jsonb);
begin
 if viewer is null then raise exception 'Sesión requerida'; end if;
 if provided_client_session_id is null or char_length(provided_client_session_id) not between 8 and 120 or provided_client_session_id !~ '^[A-Za-z0-9:_-]+$' then raise exception 'client_session_id no válido'; end if;
 select * into route_row from public.learning_routes where route_code=target_route_code and status='published'; if route_row.id is null then raise exception 'Ruta no disponible'; end if;
 if not private.has_institution_role(route_row.school_id,array['student'::public.institution_role]) then raise exception 'Solo un estudiante activo puede iniciar una lección'; end if;
 select * into lesson_row from public.learning_lessons where id=target_lesson_id and route_id=route_row.id; if lesson_row.id is null then raise exception 'La lección no pertenece a esta versión de la ruta'; end if;
 select * into existing from public.practice_sessions where student_id=viewer and client_session_id=provided_client_session_id; if existing.id is not null then return jsonb_build_object('session_id',existing.id,'recovered',true,'status',existing.status,'expected_evaluable',lesson_row.unit_count*4); end if;
 select coalesce(array_agg(lu.word_id order by lu.lesson_unit_position) filter(where wp.word_id is null or wp.next_review_at<=clock_timestamp()),'{}'::uuid[]) into eligible from public.learning_lesson_units lu left join public.student_word_progress wp on wp.student_id=viewer and wp.word_id=lu.word_id where lu.lesson_id=lesson_row.id;
 insert into public.practice_sessions(student_id,client_session_id,source,source_id,route_id,lesson_id,session_kind,run_mode,status,last_activity_at,client_context,reward_eligible_word_ids) values(viewer,provided_client_session_id,'free_practice',lesson_row.id,route_row.id,lesson_row.id,'learning','normal','in_progress',clock_timestamp(),ctx,eligible) returning id into created_id;
 insert into public.student_lesson_progress(student_id,route_id,lesson_id,status,mastery_status,unlocked_at,started_at,updated_at) values(viewer,route_row.id,lesson_row.id,'in_progress','in_progress',clock_timestamp(),clock_timestamp(),clock_timestamp()) on conflict(student_id,route_id,lesson_id) do update set started_at=coalesce(public.student_lesson_progress.started_at,excluded.started_at),updated_at=clock_timestamp();
 return jsonb_build_object('session_id',created_id,'recovered',false,'status','in_progress','route_code',route_row.route_code,'lesson_id',lesson_row.id,'expected_evaluable',lesson_row.unit_count*4);
end $$;

create or replace function public.record_route_lesson_attempt_v1(target_session_id uuid,target_word_id uuid,target_activity_type public.activity_type,provided_answer text,provided_response_time_ms integer,provided_client_event_id text,provided_attempt_number smallint default 1) returns jsonb language plpgsql security definer set search_path='' as $$
declare viewer uuid:=auth.uid(); s public.practice_sessions%rowtype; existing public.practice_attempts%rowtype; w public.vocabulary_words%rowtype; unit_pos smallint; activity_pos smallint; norm text; expected jsonb; ok boolean; eligible boolean; created bigint; outcome public.attempt_outcome;
begin
 if viewer is null then raise exception 'Sesión requerida'; end if;
 select * into s from public.practice_sessions where id=target_session_id and student_id=viewer; if s.id is null then raise exception 'Sesión de ruta no disponible'; end if;
 select * into existing from public.practice_attempts where session_id=s.id and client_event_id=provided_client_event_id; if existing.id is not null then return jsonb_build_object('attempt_id',existing.id,'correct',existing.is_correct,'idempotent_replay',true); end if;
 if s.status<>'in_progress' then raise exception 'La sesión ya terminó'; end if;
 select lu.lesson_unit_position into unit_pos from public.learning_lesson_units lu where lu.lesson_id=s.lesson_id and lu.word_id=target_word_id; if unit_pos is null then raise exception 'La unidad no pertenece a esta lección'; end if;
 norm:=private.normalize_practice_answer(provided_answer); select * into w from public.vocabulary_words where id=target_word_id;
 if target_activity_type='association' then expected:=jsonb_build_array(w.spanish); else select coalesce(jsonb_agg(distinct x.val),'[]'::jsonb) into expected from (select w.english val union all select value from jsonb_array_elements_text(w.accepted_forms)) x where nullif(trim(x.val),'') is not null; end if;
 ok:=exists(select 1 from jsonb_array_elements_text(expected) e(answer) where private.normalize_practice_answer(e.answer)=norm); outcome:=case when norm='' then 'no_answer'::public.attempt_outcome when ok then 'correct'::public.attempt_outcome else 'incorrect'::public.attempt_outcome end;
 activity_pos:=case target_activity_type when 'association' then 1 when 'listening' then 2 when 'writing' then 3 else 4 end; eligible:=target_word_id=any(s.reward_eligible_word_ids);
 insert into public.practice_attempts(session_id,word_id,activity_type,answer_text,answer_normalized,is_correct,response_time_ms,attempt_number,client_event_id,outcome,source,source_id,counts_for_mastery,can_generate_reward,lesson_unit_position,activity_position) values(s.id,target_word_id,target_activity_type,provided_answer,norm,ok,greatest(0,least(coalesce(provided_response_time_ms,0),120000)),provided_attempt_number,provided_client_event_id,outcome,s.source,s.source_id,eligible,eligible,unit_pos,activity_pos) returning id into created;
 return jsonb_build_object('attempt_id',created,'correct',ok,'idempotent_replay',false,'counts_for_mastery',eligible,'can_generate_reward',eligible);
end $$;

create or replace function public.complete_route_lesson_session_v1(target_session_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$
declare viewer uuid:=auth.uid(); s public.practice_sessions%rowtype; r public.learning_routes%rowtype; l public.learning_lessons%rowtype; receipt jsonb; result jsonb; expected_count integer; actual_count integer; correct_count integer; pct numeric; mastered boolean; eligible_total integer; eligible_correct integer; earned_xp integer:=0; earned_coins integer:=0; review record; prev public.student_word_progress%rowtype; pass boolean; new_interval integer; new_streak integer; new_state public.mastery_state; next_at timestamptz;
begin
 if viewer is null then raise exception 'Sesión requerida'; end if;
 select psr.result into receipt from private.practice_session_receipts psr where psr.session_id=target_session_id and psr.student_id=viewer; if receipt is not null then return receipt||jsonb_build_object('idempotent_replay',true); end if;
 select * into s from public.practice_sessions where id=target_session_id and student_id=viewer for update; if s.id is null then raise exception 'Sesión de ruta no disponible'; end if;
 select * into r from public.learning_routes where id=s.route_id; select * into l from public.learning_lessons where id=s.lesson_id;
 expected_count:=l.unit_count*4; select count(*)::integer,count(*) filter(where is_correct)::integer into actual_count,correct_count from public.practice_attempts where session_id=s.id and lesson_unit_position is not null; if actual_count<>expected_count then raise exception 'La lección aún no tiene todos los momentos evaluables registrados'; end if;
 pct:=round(correct_count::numeric*100/expected_count,2); mastered:=(correct_count::numeric/expected_count)>=r.mastery_threshold;
 select count(*)::integer,count(*) filter(where is_correct)::integer into eligible_total,eligible_correct from public.practice_attempts where session_id=s.id and can_generate_reward; if eligible_total>0 then earned_xp:=eligible_correct*20+15; earned_coins:=eligible_correct*3; end if;
 for review in select a.word_id,count(*)::integer attempts,count(*) filter(where a.is_correct)::integer corrects,coalesce(round(avg(a.response_time_ms)),0)::integer avg_ms from public.practice_attempts a where a.session_id=s.id and a.counts_for_mastery group by a.word_id loop
   select * into prev from public.student_word_progress where student_id=viewer and word_id=review.word_id; if not found then prev.interval_days:=0; prev.ease_factor:=2.30; prev.correct_streak:=0; prev.total_attempts:=0; prev.correct_attempts:=0; end if;
   pass:=review.corrects::numeric/review.attempts>=0.75; new_streak:=case when pass then coalesce(prev.correct_streak,0)+1 else 0 end; new_interval:=case when not pass then 0 when coalesce(prev.interval_days,0)=0 then 1 when prev.interval_days=1 then 3 else greatest(4,round(prev.interval_days*coalesce(prev.ease_factor,2.30))::integer) end; new_state:=case when not pass then 'learning'::public.mastery_state when new_streak>=5 and new_interval>=21 then 'mastered'::public.mastery_state when new_streak>=2 then 'review'::public.mastery_state else 'learning'::public.mastery_state end; next_at:=case when review.corrects=review.attempts then clock_timestamp()+make_interval(days=>new_interval) else clock_timestamp() end;
   insert into public.student_word_progress(student_id,word_id,mastery_state,interval_days,ease_factor,correct_streak,total_attempts,correct_attempts,last_response_time_ms,last_reviewed_at,next_review_at,mastered_at,last_change_source) values(viewer,review.word_id,new_state,new_interval,coalesce(prev.ease_factor,2.30),new_streak,coalesce(prev.total_attempts,0)+review.attempts,coalesce(prev.correct_attempts,0)+review.corrects,review.avg_ms,clock_timestamp(),next_at,case when new_state='mastered' then coalesce(prev.mastered_at,clock_timestamp()) else prev.mastered_at end,'route_lesson') on conflict(student_id,word_id) do update set mastery_state=excluded.mastery_state,interval_days=excluded.interval_days,correct_streak=excluded.correct_streak,total_attempts=excluded.total_attempts,correct_attempts=excluded.correct_attempts,last_reviewed_at=excluded.last_reviewed_at,next_review_at=excluded.next_review_at,mastered_at=excluded.mastered_at,last_change_source='route_lesson',updated_at=clock_timestamp();
 end loop;
 result:=jsonb_build_object('correct',correct_count,'total',expected_count,'percentage',pct,'mastered',mastered,'xp',earned_xp,'coins',earned_coins,'idempotent_replay',false);
 insert into public.student_lesson_progress(student_id,route_id,lesson_id,status,mastery_status,finished_at,attempt_count,last_attempt_at,last_correct,last_total,last_percentage,best_correct,best_total,best_percentage,last_result,best_result,updated_at) values(viewer,r.id,l.id,'finished',case when mastered then 'mastered' else 'needs_review' end,clock_timestamp(),1,clock_timestamp(),correct_count,expected_count,pct,correct_count,expected_count,pct,result,result,clock_timestamp()) on conflict(student_id,route_id,lesson_id) do update set status='finished',mastery_status=excluded.mastery_status,finished_at=coalesce(public.student_lesson_progress.finished_at,excluded.finished_at),attempt_count=public.student_lesson_progress.attempt_count+1,last_attempt_at=excluded.last_attempt_at,last_correct=excluded.last_correct,last_total=excluded.last_total,last_percentage=excluded.last_percentage,last_result=excluded.last_result,best_percentage=greatest(public.student_lesson_progress.best_percentage,excluded.last_percentage),updated_at=clock_timestamp();
 insert into public.reward_events(student_id,client_event_id,source,source_id,xp_delta,coin_delta,reason) values(viewer,'route-session:'||s.id::text,'free_practice',s.id,earned_xp,earned_coins,'route_lesson_completion') on conflict(student_id,client_event_id,reason) do nothing;
 if eligible_total>0 then insert into public.student_stats(student_id,total_xp,coins,current_streak,longest_streak,last_practice_date) values(viewer,earned_xp,earned_coins,1,1,current_date) on conflict(student_id) do update set total_xp=public.student_stats.total_xp+excluded.total_xp,coins=public.student_stats.coins+excluded.coins,updated_at=clock_timestamp(); end if;
 update public.practice_sessions set completed_at=clock_timestamp(),status='completed',xp_earned=earned_xp,coins_earned=earned_coins where id=s.id; insert into private.practice_session_receipts(session_id,student_id,result) values(s.id,viewer,result); return result;
end $$;

alter table public.profiles enable row level security; alter table public.schools enable row level security; alter table public.groups enable row level security; alter table public.group_members enable row level security; alter table public.practice_sessions enable row level security; alter table public.practice_attempts enable row level security; alter table public.student_word_progress enable row level security; alter table public.student_lesson_progress enable row level security; alter table public.student_stats enable row level security; alter table public.reward_events enable row level security; alter table public.learning_routes enable row level security; alter table public.learning_lessons enable row level security; alter table public.learning_lesson_units enable row level security;

create policy "profiles_read" on public.profiles for select to authenticated using(id=auth.uid() or private.shares_group_with(id) or (school_id is not null and private.has_institution_role(school_id,array['institution_admin'::public.institution_role,'superadmin'::public.institution_role])));
create policy "schools_read" on public.schools for select to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.school_id=schools.id));
create policy "groups_read" on public.groups for select to authenticated using(private.can_manage_group(id) or private.is_group_member(id));
create policy "group_members_read" on public.group_members for select to authenticated using(student_id=auth.uid() or private.can_manage_group(group_id));
create policy "sessions_read" on public.practice_sessions for select to authenticated using(student_id=auth.uid() or private.shares_group_with(student_id));
create policy "attempts_read" on public.practice_attempts for select to authenticated using(exists(select 1 from public.practice_sessions s where s.id=practice_attempts.session_id and (s.student_id=auth.uid() or private.shares_group_with(s.student_id))));
create policy "word_progress_read" on public.student_word_progress for select to authenticated using(student_id=auth.uid() or private.shares_group_with(student_id));
create policy "lesson_progress_read" on public.student_lesson_progress for select to authenticated using(student_id=auth.uid() or private.shares_group_with(student_id));
create policy "stats_read" on public.student_stats for select to authenticated using(student_id=auth.uid() or private.shares_group_with(student_id));
create policy "reward_read" on public.reward_events for select to authenticated using(student_id=auth.uid());
create policy "published_routes_read" on public.learning_routes for select to anon,authenticated using(status='published');
create policy "published_lessons_read" on public.learning_lessons for select to anon,authenticated using(exists(select 1 from public.learning_routes r where r.id=learning_lessons.route_id and r.status='published'));
create policy "published_units_read" on public.learning_lesson_units for select to anon,authenticated using(exists(select 1 from public.learning_lessons l join public.learning_routes r on r.id=l.route_id where l.id=learning_lesson_units.lesson_id and r.status='published'));

grant usage on schema public to anon,authenticated; grant select on public.learning_routes,public.learning_lessons,public.learning_lesson_units,public.vocabulary_words to anon,authenticated; grant select on public.profiles,public.schools,public.groups,public.group_members,public.practice_sessions,public.practice_attempts,public.student_word_progress,public.student_lesson_progress,public.student_stats,public.reward_events to authenticated;
revoke all on all tables in schema private from anon,authenticated;
revoke all on function public.start_route_lesson_session_v1(text,uuid,text,jsonb) from public,anon; grant execute on function public.start_route_lesson_session_v1(text,uuid,text,jsonb) to authenticated;
revoke all on function public.record_route_lesson_attempt_v1(uuid,uuid,public.activity_type,text,integer,text,smallint) from public,anon; grant execute on function public.record_route_lesson_attempt_v1(uuid,uuid,public.activity_type,text,integer,text,smallint) to authenticated;
revoke all on function public.complete_route_lesson_session_v1(uuid) from public,anon; grant execute on function public.complete_route_lesson_session_v1(uuid) to authenticated;
revoke all on function public.get_my_auth_context() from public,anon; grant execute on function public.get_my_auth_context() to authenticated;
